//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.22 at 12:05:04 PM CEST 
//


package generated;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for rezepteType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rezepteType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rezept" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rezeptname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="beschreibung" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fotos">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="foto" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="benutzername" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="adresse" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="arbeitszeit" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *                   &lt;element name="kochbackzeit" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *                   &lt;element name="ruhezeit" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *                   &lt;element name="schwierigkeitsgrad">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="simpel"/>
 *                         &lt;enumeration value="normal"/>
 *                         &lt;enumeration value="schwer"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="brennwert" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;union>
 *                         &lt;simpleType>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *                           &lt;/restriction>
 *                         &lt;/simpleType>
 *                         &lt;simpleType>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                             &lt;enumeration value="keine Angabe"/>
 *                           &lt;/restriction>
 *                         &lt;/simpleType>
 *                       &lt;/union>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="portionen" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                   &lt;element name="zutaten">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="zutat" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="menge" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="zaehler" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                                                 &lt;element name="nenner" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="einheit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="zubereitung" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="kommentare">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="kommentar" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="benutzername" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="avatar" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                                       &lt;element name="geschrieben_am" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                       &lt;element name="nachricht" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rezepteType", propOrder = {
    "rezept"
})
public class RezepteType {

    protected List<RezepteType.Rezept> rezept;

    /**
     * Gets the value of the rezept property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rezept property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRezept().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RezepteType.Rezept }
     * 
     * 
     */
    public List<RezepteType.Rezept> getRezept() {
        if (rezept == null) {
            rezept = new ArrayList<RezepteType.Rezept>();
        }
        return this.rezept;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="rezeptname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="beschreibung" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fotos">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="foto" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="benutzername" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="adresse" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="arbeitszeit" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
     *         &lt;element name="kochbackzeit" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
     *         &lt;element name="ruhezeit" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
     *         &lt;element name="schwierigkeitsgrad">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="simpel"/>
     *               &lt;enumeration value="normal"/>
     *               &lt;enumeration value="schwer"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="brennwert" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;union>
     *               &lt;simpleType>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
     *                 &lt;/restriction>
     *               &lt;/simpleType>
     *               &lt;simpleType>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                   &lt;enumeration value="keine Angabe"/>
     *                 &lt;/restriction>
     *               &lt;/simpleType>
     *             &lt;/union>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="portionen" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *         &lt;element name="zutaten">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="zutat" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="menge" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="zaehler" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *                                       &lt;element name="nenner" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="einheit" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="zubereitung" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="kommentare">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="kommentar" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="benutzername" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="avatar" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                             &lt;element name="geschrieben_am" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                             &lt;element name="nachricht" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rezeptname",
        "beschreibung",
        "fotos",
        "arbeitszeit",
        "kochbackzeit",
        "ruhezeit",
        "schwierigkeitsgrad",
        "brennwert",
        "portionen",
        "zutaten",
        "zubereitung",
        "kommentare"
    })
    public static class Rezept {

        @XmlElement(required = true)
        protected String rezeptname;
        @XmlElement(required = true)
        protected String beschreibung;
        @XmlElement(required = true)
        protected RezepteType.Rezept.Fotos fotos;
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger arbeitszeit;
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger kochbackzeit;
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger ruhezeit;
        @XmlElement(required = true)
        protected String schwierigkeitsgrad;
        protected String brennwert;
        @XmlElement(required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger portionen;
        @XmlElement(required = true)
        protected RezepteType.Rezept.Zutaten zutaten;
        @XmlElement(required = true)
        protected String zubereitung;
        @XmlElement(required = true)
        protected RezepteType.Rezept.Kommentare kommentare;

        /**
         * Gets the value of the rezeptname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRezeptname() {
            return rezeptname;
        }

        /**
         * Sets the value of the rezeptname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRezeptname(String value) {
            this.rezeptname = value;
        }

        /**
         * Gets the value of the beschreibung property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBeschreibung() {
            return beschreibung;
        }

        /**
         * Sets the value of the beschreibung property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBeschreibung(String value) {
            this.beschreibung = value;
        }

        /**
         * Gets the value of the fotos property.
         * 
         * @return
         *     possible object is
         *     {@link RezepteType.Rezept.Fotos }
         *     
         */
        public RezepteType.Rezept.Fotos getFotos() {
            return fotos;
        }

        /**
         * Sets the value of the fotos property.
         * 
         * @param value
         *     allowed object is
         *     {@link RezepteType.Rezept.Fotos }
         *     
         */
        public void setFotos(RezepteType.Rezept.Fotos value) {
            this.fotos = value;
        }

        /**
         * Gets the value of the arbeitszeit property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getArbeitszeit() {
            return arbeitszeit;
        }

        /**
         * Sets the value of the arbeitszeit property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setArbeitszeit(BigInteger value) {
            this.arbeitszeit = value;
        }

        /**
         * Gets the value of the kochbackzeit property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getKochbackzeit() {
            return kochbackzeit;
        }

        /**
         * Sets the value of the kochbackzeit property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setKochbackzeit(BigInteger value) {
            this.kochbackzeit = value;
        }

        /**
         * Gets the value of the ruhezeit property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getRuhezeit() {
            return ruhezeit;
        }

        /**
         * Sets the value of the ruhezeit property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setRuhezeit(BigInteger value) {
            this.ruhezeit = value;
        }

        /**
         * Gets the value of the schwierigkeitsgrad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSchwierigkeitsgrad() {
            return schwierigkeitsgrad;
        }

        /**
         * Sets the value of the schwierigkeitsgrad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSchwierigkeitsgrad(String value) {
            this.schwierigkeitsgrad = value;
        }

        /**
         * Gets the value of the brennwert property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrennwert() {
            return brennwert;
        }

        /**
         * Sets the value of the brennwert property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrennwert(String value) {
            this.brennwert = value;
        }

        /**
         * Gets the value of the portionen property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPortionen() {
            return portionen;
        }

        /**
         * Sets the value of the portionen property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPortionen(BigInteger value) {
            this.portionen = value;
        }

        /**
         * Gets the value of the zutaten property.
         * 
         * @return
         *     possible object is
         *     {@link RezepteType.Rezept.Zutaten }
         *     
         */
        public RezepteType.Rezept.Zutaten getZutaten() {
            return zutaten;
        }

        /**
         * Sets the value of the zutaten property.
         * 
         * @param value
         *     allowed object is
         *     {@link RezepteType.Rezept.Zutaten }
         *     
         */
        public void setZutaten(RezepteType.Rezept.Zutaten value) {
            this.zutaten = value;
        }

        /**
         * Gets the value of the zubereitung property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZubereitung() {
            return zubereitung;
        }

        /**
         * Sets the value of the zubereitung property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZubereitung(String value) {
            this.zubereitung = value;
        }

        /**
         * Gets the value of the kommentare property.
         * 
         * @return
         *     possible object is
         *     {@link RezepteType.Rezept.Kommentare }
         *     
         */
        public RezepteType.Rezept.Kommentare getKommentare() {
            return kommentare;
        }

        /**
         * Sets the value of the kommentare property.
         * 
         * @param value
         *     allowed object is
         *     {@link RezepteType.Rezept.Kommentare }
         *     
         */
        public void setKommentare(RezepteType.Rezept.Kommentare value) {
            this.kommentare = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="foto" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="benutzername" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="adresse" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "foto"
        })
        public static class Fotos {

            protected List<RezepteType.Rezept.Fotos.Foto> foto;

            /**
             * Gets the value of the foto property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the foto property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getFoto().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link RezepteType.Rezept.Fotos.Foto }
             * 
             * 
             */
            public List<RezepteType.Rezept.Fotos.Foto> getFoto() {
                if (foto == null) {
                    foto = new ArrayList<RezepteType.Rezept.Fotos.Foto>();
                }
                return this.foto;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="benutzername" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="adresse" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "benutzername",
                "adresse"
            })
            public static class Foto {

                @XmlElement(required = true)
                protected String benutzername;
                @XmlElement(required = true)
                @XmlSchemaType(name = "anyURI")
                protected String adresse;

                /**
                 * Gets the value of the benutzername property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBenutzername() {
                    return benutzername;
                }

                /**
                 * Sets the value of the benutzername property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBenutzername(String value) {
                    this.benutzername = value;
                }

                /**
                 * Gets the value of the adresse property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAdresse() {
                    return adresse;
                }

                /**
                 * Sets the value of the adresse property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAdresse(String value) {
                    this.adresse = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="kommentar" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="benutzername" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="avatar" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *                   &lt;element name="geschrieben_am" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                   &lt;element name="nachricht" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "kommentar"
        })
        public static class Kommentare {

            protected List<RezepteType.Rezept.Kommentare.Kommentar> kommentar;

            /**
             * Gets the value of the kommentar property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the kommentar property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getKommentar().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link RezepteType.Rezept.Kommentare.Kommentar }
             * 
             * 
             */
            public List<RezepteType.Rezept.Kommentare.Kommentar> getKommentar() {
                if (kommentar == null) {
                    kommentar = new ArrayList<RezepteType.Rezept.Kommentare.Kommentar>();
                }
                return this.kommentar;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="benutzername" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="avatar" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
             *         &lt;element name="geschrieben_am" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *         &lt;element name="nachricht" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "benutzername",
                "avatar",
                "geschriebenAm",
                "nachricht"
            })
            public static class Kommentar {

                @XmlElement(required = true)
                protected String benutzername;
                @XmlElement(required = true)
                @XmlSchemaType(name = "anyURI")
                protected String avatar;
                @XmlElement(name = "geschrieben_am", required = true)
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar geschriebenAm;
                @XmlElement(required = true)
                protected String nachricht;

                /**
                 * Gets the value of the benutzername property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBenutzername() {
                    return benutzername;
                }

                /**
                 * Sets the value of the benutzername property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBenutzername(String value) {
                    this.benutzername = value;
                }

                /**
                 * Gets the value of the avatar property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAvatar() {
                    return avatar;
                }

                /**
                 * Sets the value of the avatar property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAvatar(String value) {
                    this.avatar = value;
                }

                /**
                 * Gets the value of the geschriebenAm property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getGeschriebenAm() {
                    return geschriebenAm;
                }

                /**
                 * Sets the value of the geschriebenAm property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setGeschriebenAm(XMLGregorianCalendar value) {
                    this.geschriebenAm = value;
                }

                /**
                 * Gets the value of the nachricht property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNachricht() {
                    return nachricht;
                }

                /**
                 * Sets the value of the nachricht property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNachricht(String value) {
                    this.nachricht = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="zutat" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="menge" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="zaehler" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
         *                             &lt;element name="nenner" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
         *                           &lt;/sequence>
         *                           &lt;attribute name="einheit" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "zutat"
        })
        public static class Zutaten {

            @XmlElement(required = true)
            protected List<RezepteType.Rezept.Zutaten.Zutat> zutat;

            /**
             * Gets the value of the zutat property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the zutat property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getZutat().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link RezepteType.Rezept.Zutaten.Zutat }
             * 
             * 
             */
            public List<RezepteType.Rezept.Zutaten.Zutat> getZutat() {
                if (zutat == null) {
                    zutat = new ArrayList<RezepteType.Rezept.Zutaten.Zutat>();
                }
                return this.zutat;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="menge" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="zaehler" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
             *                   &lt;element name="nenner" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
             *                 &lt;/sequence>
             *                 &lt;attribute name="einheit" type="{http://www.w3.org/2001/XMLSchema}string" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "name",
                "menge"
            })
            public static class Zutat {

                @XmlElement(required = true)
                protected String name;
                protected RezepteType.Rezept.Zutaten.Zutat.Menge menge;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the menge property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link RezepteType.Rezept.Zutaten.Zutat.Menge }
                 *     
                 */
                public RezepteType.Rezept.Zutaten.Zutat.Menge getMenge() {
                    return menge;
                }

                /**
                 * Sets the value of the menge property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link RezepteType.Rezept.Zutaten.Zutat.Menge }
                 *     
                 */
                public void setMenge(RezepteType.Rezept.Zutaten.Zutat.Menge value) {
                    this.menge = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="zaehler" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
                 *         &lt;element name="nenner" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
                 *       &lt;/sequence>
                 *       &lt;attribute name="einheit" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "zaehler",
                    "nenner"
                })
                public static class Menge {

                    @XmlElement(required = true)
                    @XmlSchemaType(name = "positiveInteger")
                    protected BigInteger zaehler;
                    @XmlSchemaType(name = "positiveInteger")
                    protected BigInteger nenner;
                    @XmlAttribute(name = "einheit")
                    protected String einheit;

                    /**
                     * Gets the value of the zaehler property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigInteger }
                     *     
                     */
                    public BigInteger getZaehler() {
                        return zaehler;
                    }

                    /**
                     * Sets the value of the zaehler property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigInteger }
                     *     
                     */
                    public void setZaehler(BigInteger value) {
                        this.zaehler = value;
                    }

                    /**
                     * Gets the value of the nenner property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigInteger }
                     *     
                     */
                    public BigInteger getNenner() {
                        return nenner;
                    }

                    /**
                     * Sets the value of the nenner property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigInteger }
                     *     
                     */
                    public void setNenner(BigInteger value) {
                        this.nenner = value;
                    }

                    /**
                     * Gets the value of the einheit property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getEinheit() {
                        return einheit;
                    }

                    /**
                     * Sets the value of the einheit property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setEinheit(String value) {
                        this.einheit = value;
                    }

                }

            }

        }

    }

}
